const enUS = {
  hello: 'Hello, Howard!',
  update: 'Update',
  add: 'Add',
  essentialInformation: 'Essential information',
  /* 合作机构 start */
  legalRepresentativeName: 'Legal Representative Name',
  cooperativeManagement: 'Cooperative management',
  cooperativeOrganizationCode: 'Cooperative Organization Code',
  cooperativeOrganizationChineseName: 'Chinese Name Of Cooperative Organization',
  cooperativeOrganizationChineseShortName: 'Chinese Abbreviation For Cooperative Organization',
  cooperativeOrganizationEnglishName: 'English Name Of Cooperative Organization',
  cooperativeOrganizationEnglishShortName: 'English Abbreviation For Cooperative Organization',
  uniformSocialCreditCode: 'Uniform social credit code or organizational code',
  registrationDate: 'Registration Or Approval Date Of Establishment',
  registrationAddress: 'Registered Address',
  cooperativeState: 'Cooperative state',
  /* 合作机构 end */
  view: 'View',
  delete: 'Delete',
  pageTotal: 'Total',
  pageItem: 'Item',
  signOut: 'Sign out',
  switchTheme: 'Switch Theme',
  addLevel: 'Add Power',
  save: 'Save',
  cancel: 'Cancel',
  search: 'Search',
  reset: 'Reset',
  levelNumber: 'Power Level',
  levelName: 'Power Name',
  node: {
    addMenu: 'Add Menu',
    menuName: 'Menu Name',
    menuEnName: 'English Menu Name',
    menuLevel: 'Menu Level',
    subordinateMenu: 'Subordinate Menu',
    menuUrl: 'Menu Url',
    Enable: 'Enable',
    sequenceNumber: 'Sequence Number',
    creationTime: 'Creation Time',
    founder: 'Founder',
  },
  organiz: {
    // 用户管理
    affiliatedInstitution: 'Affiliated Institution',
    sysId: 'System Id',
    userName: 'User Name',
    idType: 'Id Type',
    idNumber: 'Id Number',
    password: 'Password',
    phoneNumber: 'Phone Number',
    email: 'E-mail',
    userRights: 'User Rights',
    userStatus: 'User Status',
    // 机构管理、部门管理
    organizationCode: 'Organization Code',
    organizationtInfo: 'Organization Code',
    organizationName: 'Organization Name',
    numberOfAgencies: 'Number Of Agencies',
    departmentLevel: 'Department Level',
    departmentName: 'Department Name',
    headOfDepartment: 'Head Of Department',
    sectorNumber: 'Sector Number',
  },
}
export default enUS
