module.exports = [
  {
    id: 1,
    icon: 'laptop',
    bpid: 1,
    name: '个人中心',
    route: '/routes/',
    clickAble: true,
  },
  {
    id: 11,
    bpid: 1,
    mpid: 1,
    name: '我的活动',
    route: '/routes/activityManage',
    clickAble: true,
  },
  {
    id: 111,
    bpid: 11,
    mpid: 11,
    name: '新建活动',
    route: '/routes/newActivity',
    clickAble: true,
  },
  // {
  //   id: 4,
  //   bpid: 1,
  //   name: '收款管理',
  //   icon: 'user',
  //   route: '/user',
  //   clickAble: true,
  // },
  // {
  //   id: 4,
  //   bpid: 1,
  //   name: '状态管理',
  //   icon: 'user',
  //   route: '/user',
  //   clickAble: true,
  // },
  // {
  //   id: 31,
  //   bpid: 3,
  //   mpid: 3,
  //   name: 'serviceParams',
  //   icon: 'setting',
  //   route: '/sysConfig/serviceParams',
  //   // clickAble: false,
  // },
  // {
  //   id: 311,
  //   bpid: 31,
  //   mpid: 31,
  //   name: 'loanTypes',
  //   icon: 'setting',
  //   route: '/sysConfig/serviceParams/loanTypes',
  //   // clickAble: false,
  // },
  // {
  //   id: 312,
  //   bpid: 31,
  //   mpid: 31,
  //   name: 'eCharts',
  //   icon: 'area-chart',
  //   route: '/sysConfig/serviceParams/eCharts',
  //   // clickAble: false,
  // },
]
