module.exports = [
  {
    id: 1,
    icon: '',
    bpid: 1,
    name: '首页',
    route: '/routes/pageHome',
    clickAble: true,
  },
  {
    id: 2,
    bpid: 1,
    name: '相册展示',
    icon: '',
    route: '/routes/albumShow',
    clickAble: true,
  },
  // {
  //   id: 1,
  //   bpid: 1,
  //   name: 'logo',
  //   icon: 'setting',
  //   router: '/sysConfig',
  //   // clickAble: false,
  // },
  // {
  //   id: 4,
  //   bpid: 1,
  //   name: '收款管理',
  //   icon: 'user',
  //   router: '/user',
  //   clickAble: true,
  // },
  // {
  //   id: 4,
  //   bpid: 1,
  //   name: '状态管理',
  //   icon: 'user',
  //   router: '/user',
  //   clickAble: true,
  // },
  // {
  //   id: 31,
  //   bpid: 3,
  //   mpid: 3,
  //   name: 'serviceParams',
  //   icon: 'setting',
  //   router: '/sysConfig/serviceParams',
  //   // clickAble: false,
  // },
  // {
  //   id: 311,
  //   bpid: 31,
  //   mpid: 31,
  //   name: 'loanTypes',
  //   icon: 'setting',
  //   router: '/sysConfig/serviceParams/loanTypes',
  //   // clickAble: false,
  // },
  // {
  //   id: 312,
  //   bpid: 31,
  //   mpid: 31,
  //   name: 'eCharts',
  //   icon: 'area-chart',
  //   router: '/sysConfig/serviceParams/eCharts',
  //   // clickAble: false,
  // },
]
