const zhCN = {
  hello: '你好，方浩！',
  update: '修改',
  add: '新增',
  essentialInformation: '基本信息',
  /* 合作机构 start */
  cooperativeManagement: '合作机构管理',
  legalRepresentativeName: '法定代表人姓名',
  cooperativeOrganizationCode: '合作机构代码',
  cooperativeOrganizationChineseName: '合作组织中文名称',
  cooperativeOrganizationChineseShortName: '合作机构中文简称',
  cooperativeOrganizationEnglishName: '合作机构英文名称',
  cooperativeOrganizationEnglishShortName: '合作机构英文简称',
  uniformSocialCreditCode: '统一社会信用代码或组织机构代码',
  registrationDate: '注册或批准成立日期',
  registrationAddress: '注册地址',
  cooperativeState: '合作状态',
  /* 合作机构 end */
  view: '查看',
  delete: '删除',
  pageTotal: '共',
  pageItem: '条',
  save: '保存',
  cancel: '取消',
  signOut: '退出',
  switchTheme: '切换主题',
  addLevel: '添加权限',
  levelNumber: '权限等级',
  levelName: '权限名称',
  search: '搜索',
  reset: '重置',
  node: {
    addMenu: '新增菜单',
    addMenuTitle: '新增菜单',
    menuName: '菜单名称',
    menuEnName: '菜单英文名称',
    menuLevel: '菜单等级',
    subordinateMenu: '所属菜单',
    menuUrl: '菜单路径',
    Enable: '是否启用',
    sequenceNumber: '顺序号',
    creationTime: '创建时间',
    founder: '创建人',
  },
  organiz: {
    // 用户管理
    affiliatedInstitution: '所属机构',
    sysId: '所属系统',
    userName: '用户名称',
    idType: '证件类型',
    idNumber: '证件号码',
    password: '密码',
    phoneNumber: '手机',
    email: '邮箱',
    userRights: '用户权限',
    userStatus: '用户状态',
    // 机构管理、部门管理
    organizationCode: '机构编码',
    organizationtInfo: '对应机构',
    organizationName: '机构名称',
    numberOfAgencies: '机构人数',
    departmentLevel: '等级',
    departmentName: '部门名称',
    headOfDepartment: '部门负责人',
    sectorNumber: '部门人数',
  },
}
export default zhCN
